In [5]:
import numpy as np

In [9]:
A = np.array([[1.,2.,3.],[4.,5.,6.]])
M = np.mat([[1., 2., 3.], [4.,5.,6.]])

In [10]:
A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [11]:
M

matrix([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [12]:
A[1]

array([ 4.,  5.,  6.])

In [13]:
M[1]

matrix([[ 4.,  5.,  6.]])

In [15]:
A[-1]

array([ 4.,  5.,  6.])

In [16]:
M[-1]

matrix([[ 4.,  5.,  6.]])

In [22]:
M.H

matrix([[ 1.,  4.],
        [ 2.,  5.],
        [ 3.,  6.]])

In [24]:
M.T

matrix([[ 1.,  4.],
        [ 2.,  5.],
        [ 3.,  6.]])

In [25]:
A.T

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.]])

In [29]:
E = np.eye(5, 4)
E

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [32]:
D = np.diag(M)
D

array([ 1.,  5.])

In [37]:
M.H

matrix([[ 1.,  4.],
        [ 2.,  5.],
        [ 3.,  6.]])

In [44]:
M*7

matrix([[  7.,  14.,  21.],
        [ 28.,  35.,  42.]])

In [53]:
R1 = np.random.randint(0, 100,[7,3])
R2 = np.random.randint(0, 100,[3,2])
R3 = np.random.randint(0, 100,[2,1])
np.dot(R1,R2)

array([[ 9547,  1776],
       [13636,  2954],
       [14518,  4674],
       [12703,  3017],
       [12490,  2389],
       [14402,  3222],
       [ 7095,  1859]])

In [55]:
R1.T

array([[39, 76, 90, 52, 53, 84, 16],
       [77, 93, 33, 74, 98, 94, 33],
       [12,  1, 95, 65, 16,  0, 80]])

In [56]:
R1

array([[39, 77, 12],
       [76, 93,  1],
       [90, 33, 95],
       [52, 74, 65],
       [53, 98, 16],
       [84, 94,  0],
       [16, 33, 80]])

In [62]:
(a, b) = np.shape(R1)
a

7